---
# general
z_offset_scale: 5.5
visualize: false
# nodes
marker_scale: 1.0
marker_alpha: 1.0
use_sphere_marker: false
use_label: true
label_height: 1.5
label_scale: 1.25
use_bounding_box: false
bounding_box_alpha: 0.5
collapse_bounding_box: false
# edges
use_edge_source: false
interlayer_edge_scale: 0.10
interlayer_edge_alpha: 0.5
interlayer_edge_use_color: false
interlayer_edge_insertion_skip: 0
intralayer_edge_scale: 0.05
intralayer_edge_alpha: 1.0
intralayer_edge_use_color: false
intralayer_edge_insertion_skip: 0
