---
- {sub_id:  0, super_id: 1}
- {sub_id:  1, super_id: 1}
- {sub_id:  2, super_id: 1}
- {sub_id:  3, super_id: 1}
- {sub_id:  4, super_id: 2}
- {sub_id:  5, super_id: 3}
- {sub_id:  6, super_id: 2}
- {sub_id:  7, super_id: 4}
- {sub_id:  8, super_id: 4}
- {sub_id:  9, super_id: 4}
- {sub_id: 10, super_id: 4}
- {sub_id: 11, super_id: 5}
- {sub_id: 12, super_id: 5}
- {sub_id: 13, super_id: 5}
- {sub_id: 14, super_id: 5}
- {sub_id: 15, super_id: 4}
- {sub_id: 16, super_id: 6}
- {sub_id: 17, super_id: 6}
- {sub_id: 18, super_id: 6}
- {sub_id: 19, super_id: 6}
- {sub_id: 20, super_id: 7}
- {sub_id: 21, super_id: 9}
- {sub_id: 22, super_id: 7}
- {sub_id: 23, super_id: 10}
- {sub_id: 24, super_id: 8}
- {sub_id: 25, super_id: 8}
- {sub_id: 26, super_id: 11}
- {sub_id: 27, super_id: 11}
- {sub_id: 28, super_id: 11}
- {sub_id: 29, super_id: 3}
- {sub_id: 30, super_id: 3}
- {sub_id: 31, super_id: 3}
- {sub_id: 32, super_id: 0}
- {sub_id: 33, super_id: 3}
- {sub_id: 34, super_id: 11}
- {sub_id: 36, super_id: 11}
- {sub_id: 37, super_id: 3}
- {sub_id: 38, super_id: 13}
- {sub_id: 39, super_id: 7}
- {sub_id: 40, super_id: 3}
- {sub_id: 41, super_id: 13}
- {sub_id: 42, super_id: 13}
- {sub_id: 43, super_id: 13}
- {sub_id: 44, super_id: 13}
- {sub_id: 45, super_id: 3}
- {sub_id: 46, super_id: 3}
- {sub_id: 47, super_id: 3}
- {sub_id: 48, super_id: 3}
- {sub_id: 49, super_id: 14}
- {sub_id: 50, super_id: 13}
- {sub_id: 51, super_id: 13}
- {sub_id: 52, super_id: 14}
- {sub_id: 53, super_id: 14}
- {sub_id: 54, super_id: 15}
- {sub_id: 55, super_id: 15}
- {sub_id: 56, super_id: 15}
- {sub_id: 57, super_id: 2}
- {sub_id: 58, super_id: 2}
- {sub_id: 59, super_id: 2}
- {sub_id: 60, super_id: 2}
- {sub_id: 61, super_id: 3}
- {sub_id: 62, super_id: 15}
- {sub_id: 63, super_id: 5}
- {sub_id: 64, super_id: 5}
- {sub_id: 65, super_id: 5}
- {sub_id: 66, super_id: 5}
- {sub_id: 67, super_id: 5}
- {sub_id: 68, super_id: 5}
- {sub_id: 69, super_id: 5}
- {sub_id: 70, super_id: 5}
- {sub_id: 71, super_id: 5}
- {sub_id: 72, super_id: 2}
- {sub_id: 73, super_id: 2}
- {sub_id: 74, super_id: 2}
- {sub_id: 75, super_id: 2}
- {sub_id: 76, super_id: 2}
- {sub_id: 77, super_id: 2}
- {sub_id: 78, super_id: 2}
- {sub_id: 79, super_id: 2}
- {sub_id: 80, super_id: 2}
- {sub_id: 81, super_id: 2}
- {sub_id: 82, super_id: 16}
- {sub_id: 83, super_id: 16}
- {sub_id: 84, super_id: 16}
- {sub_id: 85, super_id: 16}
- {sub_id: 86, super_id: 16}
- {sub_id: 87, super_id: 16}
- {sub_id: 88, super_id: 16}
- {sub_id: 89, super_id: 16}
- {sub_id: 90, super_id: 16}
- {sub_id: 91, super_id: 2}
- {sub_id: 92, super_id: 2}
- {sub_id: 93, super_id: 11}
- {sub_id: 94, super_id: 3}
- {sub_id: 95, super_id: 3}
- {sub_id: 96, super_id: 3}
- {sub_id: 97, super_id: 3}
- {sub_id: 98, super_id: 3}
- {sub_id: 99, super_id: 3}
- {sub_id: 100, super_id: 3}
- {sub_id: 101, super_id: 2}
- {sub_id: 102, super_id: 2}
- {sub_id: 103, super_id: 2}
- {sub_id: 104, super_id: 2}
- {sub_id: 105, super_id: 2}
- {sub_id: 106, super_id: 15}
- {sub_id: 107, super_id: 15}
- {sub_id: 108, super_id: 15}
- {sub_id: 109, super_id: 15}
- {sub_id: 110, super_id: 15}
- {sub_id: 111, super_id: 15}
- {sub_id: 112, super_id: 15}
- {sub_id: 113, super_id: 15}
- {sub_id: 114, super_id: 15}
- {sub_id: 115, super_id: 15}
- {sub_id: 116, super_id: 15}
- {sub_id: 117, super_id: 15}
- {sub_id: 118, super_id: 15}
- {sub_id: 119, super_id: 2}
- {sub_id: 120, super_id: 2}
- {sub_id: 121, super_id: 2}
- {sub_id: 122, super_id: 2}
- {sub_id: 123, super_id: 2}
- {sub_id: 124, super_id: 2}
- {sub_id: 125, super_id: 2}
- {sub_id: 126, super_id: 6}
- {sub_id: 127, super_id: 6}
- {sub_id: 128, super_id: 6}
- {sub_id: 129, super_id: 2}
- {sub_id: 130, super_id: 2}
- {sub_id: 131, super_id: 17}
- {sub_id: 132, super_id: 5}
- {sub_id: 133, super_id: 9}
- {sub_id: 134, super_id: 5}
- {sub_id: 135, super_id: 5}
- {sub_id: 136, super_id: 18}
- {sub_id: 137, super_id: 18}
- {sub_id: 138, super_id: 5}
- {sub_id: 139, super_id: 18}
- {sub_id: 140, super_id: 18}
- {sub_id: 141, super_id: 18}
- {sub_id: 142, super_id: 18}
- {sub_id: 143, super_id: 3}
- {sub_id: 144, super_id: 3}
- {sub_id: 145, super_id: 3}
- {sub_id: 146, super_id: 3}
- {sub_id: 147, super_id: 3}
- {sub_id: 148, super_id: 3}
- {sub_id: 149, super_id: 3}
- {sub_id: 150, super_id: 3}
- {sub_id: 151, super_id: 3}
- {sub_id: 152, super_id: 3}
- {sub_id: 153, super_id: 3}
- {sub_id: 154, super_id: 3}
- {sub_id: 155, super_id: 3}
- {sub_id: 156, super_id: 2}
- {sub_id: 157, super_id: 3}
- {sub_id: 158, super_id: 3}
- {sub_id: 159, super_id: 3}
- {sub_id: 160, super_id: 4}
- {sub_id: 161, super_id: 8}
- {sub_id: 162, super_id: 15}
- {sub_id: 163, super_id: 13}
- {sub_id: 164, super_id: 2}
- {sub_id: 165, super_id: 12}
- {sub_id: 166, super_id: 12}
- {sub_id: 167, super_id: 2}
- {sub_id: 168, super_id: 2}
- {sub_id: 169, super_id: 8}
- {sub_id: 170, super_id: 12}
- {sub_id: 171, super_id: 12}
- {sub_id: 172, super_id: 12}
- {sub_id: 173, super_id: 12}
- {sub_id: 174, super_id: 12}
- {sub_id: 175, super_id: 12}
- {sub_id: 176, super_id: 12}
- {sub_id: 177, super_id: 12}
- {sub_id: 178, super_id: 12}
- {sub_id: 179, super_id: 12}
- {sub_id: 180, super_id: 12}
- {sub_id: 181, super_id: 12}
- {sub_id: 182, super_id: 12}
- {sub_id: 183, super_id: 12}
- {sub_id: 184, super_id: 12}
- {sub_id: 185, super_id: 12}
- {sub_id: 186, super_id: 12}
- {sub_id: 187, super_id: 12}
- {sub_id: 188, super_id: 6}
- {sub_id: 189, super_id: 6}
- {sub_id: 190, super_id: 6}
- {sub_id: 191, super_id: 2}
- {sub_id: 192, super_id: 2}
- {sub_id: 193, super_id: 3}
- {sub_id: 194, super_id: 3}
- {sub_id: 195, super_id: 12}
- {sub_id: 196, super_id: 12}
- {sub_id: 197, super_id: 12}
- {sub_id: 198, super_id: 12}
- {sub_id: 199, super_id: 0}
- {sub_id: 200, super_id: 0}
- {sub_id: 201, super_id: 17}
- {sub_id: 202, super_id: 2}
- {sub_id: 203, super_id: 16}
- {sub_id: 204, super_id: 16}
- {sub_id: 205, super_id: 16}
- {sub_id: 206, super_id: 2}
- {sub_id: 207, super_id: 11}
- {sub_id: 208, super_id: 11}
- {sub_id: 209, super_id: 2}
- {sub_id: 210, super_id: 11}
- {sub_id: 211, super_id: 11}
- {sub_id: 212, super_id: 11}
- {sub_id: 213, super_id: 11}
- {sub_id: 214, super_id: 11}
- {sub_id: 215, super_id: 11}
- {sub_id: 216, super_id: 11}
- {sub_id: 217, super_id: 11}
- {sub_id: 218, super_id: 11}

# # Super-ID mapping for tesse_cd office dataset
# 0 : Nothing
# 1 : Ventilation/Piping
# 2 : Small office objects (eg books)
# 3 : Large static wall furniture (eg bookshelf)
# 4 : Large office objects (eg boxes, carts)
# 5 : Floor (including carpet)
# 6 : Celing
# 7 : Jail cell
# 8 : Bathroom
# 9 : Bedroom
# 10: Shelving
# 11: Chairs
# 12: Walls
# 13: Doors
# 14: Elevator
# 15: Signs
# 16: Lighting
# 17: Humans
# 18: Railing
