---
lcd_visualizer_ns: /dsg/lcd_visualizer
lcd_agent_horizon_s: 3.5
descriptor_creation_horizon_m: 8.0
lcd:
  enable_agent_registration: true
  place_histogram_config: {min: 0.5, max: 2.5, bins: 30}
  num_semantic_classes: 20
  object_extraction: {fixed_radius: false, max_radius_m: 5.0, min_radius_m: 3.0, min_nodes: 10}
  places_extraction: {fixed_radius: false, max_radius_m: 5.0, min_radius_m: 3.0, min_nodes: 10}
  agent:
    min_time_separation_s: 25.0
    min_score: 0.040
    min_registration_score: 0.01        # this gets overriden
    max_registration_matches: 2
    min_score_ratio: 0.95
    min_match_separation_m: 0.0
    type: L1
  gnn_lcd:
    use_onehot_encoding: true
    onehot_encoding_dim: 39
    object_connection_radius_m: 3.0
    objects_pos_in_feature: false
    places_pos_in_feature: false
  objects:
    search:
      min_time_separation_s: 25.0
      min_score: 0.3
      min_registration_score: 0.85  # for non-GT semantics
      # min_registration_score: 0.55  # for GT semantics
      max_registration_matches: 2
      min_score_ratio: 0.95
      min_match_separation_m: 5.0
      type: L1
    registration:
      min_correspondences: 5
      min_inliers: 5
      log_registration_problem: false
      registration_output_path: ''
      recreate_subgraph: true
      subgraph_extraction: {fixed_radius: true, max_radius_m: 15.0}
  places:
    search:
      min_time_separation_s: 25.0
      min_score: 0.2
      min_registration_score: 1.5
      max_registration_matches: 2
      min_score_ratio: 0.7
      min_match_separation_m: 5.0
      type: L1
  teaser:
    estimate_scaling: false
    noise_bound: 0.10
    cbar2: 1.0
    rotation_gnc_factor: 1.4
    rotation_max_iterations: 100
    rotation_cost_threshold: 1.0e-6
    kcore_heuristic_threshold: 0.5
    inlier_selection_mode: PMC_EXACT
    max_clique_time_limit: 3600
