---
map_window:
  type: spatial
  max_radius_m: 8.0
active_window:
  volumetric_map:
    voxels_per_side: 16
    voxel_size: 0.1
    truncation_distance: 0.3
  tsdf:
    semantic_integrator:
      type: MLESemanticIntegrator
frontend:
  pgmo:
    time_horizon: 100.0
    d_graph_resolution: 2.5
    mesh_resolution: 0.005
  objects:
    min_cluster_size: 25
    cluster_tolerance: 0.18
  freespace_places:
    type: gvd
    gvd:
      max_distance_m: 4.5
      min_distance_m: 0.2
      min_diff_m: 0.1
      voronoi_config:
        mode: L1_THEN_ANGLE
        min_distance_m: 0.30
        parent_l1_separation: 20
        parent_cos_angle_separation: 0.2
    graph:
      type: CompressionGraphExtractor
      compression_distance_m: 1.0
      min_node_distance_m: 0.4
      min_edge_distance_m: 0.3
      add_heuristic_edges: true
backend:
  add_places_to_deformation_graph: true
  optimize_on_lc: true
  enable_node_merging: true
  update_functors:
    agents:
      type: UpdateAgentsFunctor
    objects:
      type: UpdateObjectsFunctor
    surface_places:
      type: Update2dPlacesFunctor
    places:
      type: UpdatePlacesFunctor
      pos_threshold_m: 0.35
      distance_tolerance_m: 0.25
    frontiers:
      type: UpdateFrontiersFunctor
    rooms:
      type: UpdateRoomsFunctor
      room_finder:
        min_dilation_m: 0.5
        max_dilation_m: 1.2
        min_component_size: 10
        min_room_size: 10
        dilation_threshold_mode: PLATEAU
        min_lifetime_length_m: 0.1
        plateau_ratio: 0.25
        clustering_mode: NEIGHBORS
        dilation_diff_threshold_m: -1.0
    buildings:
      type: UpdateBuildingsFunctor
    zmq_labels:
      type: ZmqRoomLabelUpdater
  pgmo:
    run_mode: FULL  # kimera_pgmo run mode FULL is required
    embed_trajectory_delta_t: 5.0
    num_interp_pts: 3
    interp_horizon: 10.0
    enable_sparsify: true
    trans_node_dist: 1.0
    rot_node_dist: 1.2
    rpgo:
      odom_trans_threshold: 0.05
      odom_rot_threshold: 0.01
      pcm_trans_threshold: -1
      pcm_rot_threshold: -1
      lm_diagonal_damping: true
      gnc_alpha: 0.99
      gnc_max_iterations: 500
      gnc_mu_step: 1.6
      gnc_cost_tolerance: 1.0e-05
      gnc_weight_tolerance: 1.0e-04
      gnc_fix_prev_inliers: true
      verbosity: UPDATE
      solver: LM
    add_initial_prior: true
    covariance:
      odom: 1.0e-02
      loop_close: 5.0e-02
      sg_loop_close: 1.0e-01
      prior: 1.0e-02
      mesh_mesh: 1.0
      pose_mesh: 1.0
      place_mesh: 1.0
      place_edge: 10.0
      place_merge: 10.0
      object_merge: 10.0
