---
total_semantic_labels: 51
dynamic_labels: [49, 50]
invalid_labels: [0, 1, 48]
object_labels: [2, 11, 14, 15, 16, 17, 18, 24, 26, 27, 29, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
      42, 43, 44, 45, 46, 47]
surface_place_labels: [3, 4, 5, 6, 7, 8, 9, 10, 19, 20, 21, 22, 25, 28, 30, 31]
label_names:
  - {label: 0, name: unknown}
  - {label: 1, name: sky}
  - {label: 2, name: tree}
  - {label: 3, name: water}
  - {label: 4, name: ground}
  - {label: 5, name: grass}
  - {label: 6, name: sand}
  - {label: 7, name: sidewalk}
  - {label: 8, name: dock}
  - {label: 9, name: road}
  - {label: 10, name: path}
  - {label: 11, name: vehicle}
  - {label: 12, name: building}
  - {label: 13, name: shelter}
  - {label: 14, name: signal}
  - {label: 15, name: rock}
  - {label: 16, name: fence}
  - {label: 17, name: boat}
  - {label: 18, name: sign}
  - {label: 19, name: hill}
  - {label: 20, name: bridge}
  - {label: 21, name: wall}
  - {label: 22, name: floor}
  - {label: 23, name: ceiling}
  - {label: 24, name: door}
  - {label: 25, name: stairs}
  - {label: 26, name: pole}
  - {label: 27, name: rail}
  - {label: 28, name: structure}
  - {label: 29, name: window}
  - {label: 30, name: surface}
  - {label: 31, name: flora}
  - {label: 32, name: flower}
  - {label: 33, name: bed}
  - {label: 34, name: box}
  - {label: 35, name: storage}
  - {label: 36, name: barrel}
  - {label: 37, name: bag}
  - {label: 38, name: basket}
  - {label: 39, name: seating}
  - {label: 40, name: flag}
  - {label: 41, name: decor}
  - {label: 42, name: light}
  - {label: 43, name: appliance}
  - {label: 44, name: trash}
  - {label: 45, name: bicycle}
  - {label: 46, name: food}
  - {label: 47, name: clothes}
  - {label: 48, name: thing}
  - {label: 49, name: animal}
  - {label: 50, name: human}
