---
total_semantic_labels: 21
dynamic_labels: [19, 20]
invalid_labels: [0]
object_labels:
  - 4
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
surface_place_labels: [2, 5]
label_names:
  - {label: 0, name: Unknown}
  - {label: 1, name: Wall}
  - {label: 2, name: Floor}
  - {label: 3, name: Ceiling}
  - {label: 4, name: Door}
  - {label: 5, name: Stairs}
  - {label: 6, name: Structure}
  - {label: 7, name: Shelf}
  - {label: 8, name: Plant}
  - {label: 9, name: Bed}
  - {label: 10, name: Storage}
  - {label: 11, name: Table}
  - {label: 12, name: Chair}
  - {label: 13, name: Wall_Decoration}
  - {label: 14, name: Couch}
  - {label: 15, name: Light}
  - {label: 16, name: Appliance}
  - {label: 17, name: Thing}
  - {label: 18, name: Deformable}
  - {label: 19, name: Dynamic_NonHuman}
  - {label: 20, name: Human}
