dynamic_semantic_labels: [20]
structure_labels: [0, 1, 2, 3, 4, 5, 6, 7]
object_labels: [8, 9, 10, 11, 12, 13, 14, 15, 16]
stuff_labels: [0, 1, 2, 3, 4, 5, 6, 7, 17, 18, 19]
walls_labels: [1]
floor_labels: [2, 3]
