dynamic_semantic_labels: [20]
structure_labels: [0, 3, 4, 9, 11, 14, 19]
object_labels: [5, 7, 8, 10, 18]
stuff_labels: [0, 1, 2, 3, 4, 6, 9, 11, 12, 13, 14, 15, 16, 17, 19]
walls_labels: [12, 19]
floor_labels: [3]
