---
dsg:
  add_places_to_deformation_graph: true
  optimize_on_lc: true
  enable_node_merging: true
  use_active_flag_for_updates: true
  num_neighbors_to_find_for_merge: 1
  rpgo_verbosity: update
  rpgo_solver: LM
  places_merge_pos_threshold_m: 0.35
  places_merge_distance_tolerance_m: 0.25
  merge_update_dynamic: true
  merge_update_map: {BUILDINGS: false, ROOMS: false, PLACES: true, OBJECTS: false}
pgmo:
  run_mode: FULL    # kimera_pgmo run mode FULL is required
  use_msg_time: true
  embed_trajectory_delta_t: 5.0
  num_interp_pts: 3
  interp_horizon: 10.0
  enable_sparsify: true
  trans_node_dist: 1.0
  rot_node_dist: 1.2
  rpgo:
    odom_trans_threshold: 0.05
    odom_rot_threshold: 0.01
    pcm_trans_threshold: -1
    pcm_rot_threshold: -1
    lm_diagonal_damping: true
    gnc_alpha: 0.99
    gnc_max_iterations: 100
    gnc_mu_step: 1.6
    gnc_cost_tolerance: 1.0e-05
    gnc_weight_tolerance: 1.0e-04
    gnc_fix_prev_inliers: true
    verbosity: UPDATE
    solver: LM
  add_initial_prior: false
  covariance:
    odom: 1.0e-02
    loop_close: 5.0e-02
    sg_loop_close: 1.0e-01
    prior: 1.0e-02
    mesh_mesh: 1.0e-01
    pose_mesh: 1.0e-01
    place_mesh: 1.0e-01
    place_edge: 10.0
    place_merge: 10.0
    object_merge: 10.0
building_semantic_label: 22
building_color: [169, 8, 194]
visualize_place_factors: false
enable_rooms: true
room_finder:
  min_dilation_m: 0.5
  max_dilation_m: 1.2
  min_window_size: 0.2
  clip_dilation_window_to_max: false
  min_component_size: 10
  min_room_size: 10
  dilation_threshold_mode: PLATEAU
  min_lifetime_length_m: 0.1
  plateau_ratio: 0.25
  clustering_mode: NEIGHBORS
  max_modularity_iters: 5
  modularity_gamma: 1.0
  room_prefix: R
  dilation_diff_threshold_m: -1.0
  log_filtrations: false
  log_place_graphs: false
use_2d_places:
    true
places2d_config:
    allow_places_merge: true
