# generic
z_offset_scale: 1.5
visualize: true
# node
marker_scale: 0.25
marker_alpha: 0.9
use_sphere_marker: true
use_label: false
label_height: 0.5
label_scale: 0.25
use_bounding_box: true
bounding_box_alpha: 0.3
# edge
use_edge_source: true
interlayer_edge_scale: 0.05
interlayer_edge_alpha: 0.3
interlayer_edge_use_color: true
interlayer_edge_insertion_skip: 10
intralayer_edge_scale: 0.03
intralayer_edge_alpha: 0.6
intralayer_edge_use_color: false
intralayer_edge_insertion_skip: 0
# dynamic
dynamic_num_colors: 5
dynamic_saturation: 0.9
dynamic_luminance: 0.7
dynamic_edge_sl_ratio: 0.6
dynamic_marker_scale: 0.25
dynamic_marker_alpha: 0.9
dynamic_use_sphere_marker: true
dynamic_edge_scale: 0.04
dynamic_edge_alpha: 0.9
dynamic_label_height: 0.9
dynamic_label_scale: 0.8
